# image: https://hub.docker.com/_/httpd


version: '3.8'
services:
  apache:
    container_name: ${APP_NAME}
    image: httpd:${APP_VERSION}
    restart: always
    port:
     - ${APP_PORT}:80
    volumes:
     - apache:/usr/local/apache2/htdocs
     
networks:
  default:
      name: ${APP_NAME}
    
volumes:
  apache:
    driver: local
